### ISSUE TITLE
Refined has the wrong role signature

### ISSUE THREAD

**Issue by chessai** [mrkkrp/facts#6]
Currently, it says

```haskell
type role Refined phantom representational
```

This means that I can use `coerce` to prove `Q x` given any `P x` whatsoever! I think you probably should write

```haskell
type role Refined nominal nominal
```

Why should the second parameter be nominal? Consider the interaction between `GreaterThan` and `Data.Ord.Down`.

**Comment by mrkkrp** [comment]
Well the first parameter is certainly *phantom*, I think you'll agree with that. So question is really whether or not we should allow to `coerce` between `Refined ps a` and `Refined qs a` (and choose type role annotation depending on that).

Well, my position so far is that if you use `coerce`, then you know what you're doing. It's not worth trying to really disallow this sort of coercion because there is already `assumeProp` which allows you to state that `X` holds without any proof (also not a bad thing per se and should be in the toolbox), and there is `unsafeCoerce` too.

Also I'm one of the maintainers of the `path` package which can be viewed as a specialized refined wrapper, and that package allows coercion via `coerce`, I think there has been no problem with that so far.

About the second parameter. I must admit I don't understand why it should be `nominal` either. The `Refined` type is a `newtype` and in the entire library the type `a` (second parameter) is not "inspected" in the sense described in this article:

https://ghc.haskell.org/trac/ghc/wiki/Roles

It's only used to select type class instances I guess. So why could it be problematic?

Can you show an example with `Data.Ord.Down` that exposes incorrect behavior with `representational` annotation? (Or at least describe the problematic situation in more details.)

**Comment by chessai** [comment]
I can agree with the first type variable being role-annotated as phantom as a design choice.

For the second being nominal, here is a small motivating example:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE DeriveGeneric #-}

import Control.Monad.Catch (MonadThrow)
import Data.Coerce
import GHC.Generics (Generic)
import Data.Proxy (Proxy(..))
import Data.Refined
import Data.Ord (Down(..))
import GHC.TypeLits

data GreaterThan (n :: Nat)
  deriving (Generic)

instance (Num a, Ord a, KnownNat n, Show a) => Prop a (GreaterThan n) where
  type PropProjection a (GreaterThan n) = a
  checkProp Proxy n =
    if n > fromIntegral (natVal (Proxy :: Proxy n))
      then Right n
      else Left "bad value"

g7 :: MonadThrow m => m (Refined '[GreaterThan 5] Int)
g7 = estPropThrow $ refined (7 :: Int)

-- This will compile if Refined's second type role is representational, but not nominal
notGood :: IO ()
notGood = do
  s <- g7
  let u = coerce s :: Refined '[GreaterThan 5] (Down Int)
  print $ unrefined s -- Works just fine, as it should
  print $ unrefined u -- Works just fine, as it should not, because (Down 7) is less than 5
```

**Comment by mrkkrp** [comment]
This makes sense, thank you for opening the issue!
