### ISSUE TITLE
Is it necessary for the list of properties to have kind `[Type]`?

### ISSUE THREAD

**Issue by endgame** [mrkkrp/facts#9]

**Comment by mrkkrp** [comment]
I did not see any benefits in making it poly-kinded. I don't have time to check in practice, but I'd guess that having a common ground type is the easiest way forward. Imagine you have something like `[k]`. Then you need to make sure that all properties will be of the same kind `k` so it matches every time you manipulate the list. For that you would need to make the kind of `q` in `Prop a q` also polymorphic but it's not obvious that it'll match the kind of elements in the list, it's something to impose in the signatures. It might work, but with concrete `Type` as the type of elements in the list, the problem is just not there.
